substitutions:
  device_ssid: "Ashish Wall Light"
  device_name: ashishwalllight
  device_main_description: "UT55509-RGBCW - Novostella UT55509 13W 1300lm RGBCCT Bulb."
  device_description: Ashish Wall Light
  friendly_name: "Ashish Wall Light"    # Put the name that you want to see in Home Assistant.
esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

wifi:
    ssid: !secret wifi_1st_ssid
    password: !secret wifi_1st_password

    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ap:
      ssid: ${device_ssid}
      password: !secret ap_password

captive_portal:

# Enable logging
# Example configuration entry
debug:

# Logger must be at least debug (default)
logger:
  level: debug

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

web_server:
  port: 80


output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO4
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO12
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO14
  - platform: esp8266_pwm
    id: output_cold_white
    pin: GPIO5
  - platform: esp8266_pwm
    id: output_warm_white
    pin: GPIO13

light:
  - platform: rgbww
    name: ${friendly_name}    # Put the name that you want to see in Home Assistant.
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_cold_white
    warm_white: output_warm_white
    cold_white_color_temperature: 6200 K
    warm_white_color_temperature: 3100 K
    default_transition_length: 0.5s
    constant_brightness: false
    gamma_correct: 0