substitutions:
  device_ssid: "Living Room Light"
  device_name: bathroomlight
  device_main_description: "RGBWW Ceiling LED light with RF remote located in Dining Room with discreet Tunable White & RGB Rear Light (shows up as separate lights)."
  device_description: Bathroom Light
  friendly_name: "Living Room Light - Tunable White"    # Put the name that you want to see in Home Assistant.
esphome:
  name: ${device_name}
  platform: ESP32
  board: featheresp32
#  board: nodemcu-32s

wifi:
    ssid: !secret wifi_1st_ssid
    password: !secret wifi_1st_password

    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ap:
      ssid: ${device_ssid}
      password: !secret ap_password

captive_portal:

# Enable logging
# Example configuration entry
debug:

# Logger must be at least debug (default)
logger:
  level: debug

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

web_server:
  port: 80


output:
  - platform: ledc
    id: output_cold_white
    max_power: 100%
    pin: GPIO5
  - platform: ledc
    id: output_warm_white
    pin: GPIO12
    max_power: 100%

light:
  - platform: cwww
    name: ${friendly_name}    # Put the name that you want to see in Home Assistant.
    id: ${device_name}    # id used in esphome.
    cold_white: output_cold_white
    warm_white: output_warm_white
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
    constant_brightness: false
    gamma_correct: 0
    default_transition_length: 1s