substitutions:
  device_ssid: "Dining Room Light"
  device_name: diningroomlight
  device_main_description: "RGBWW Ceiling LED light with RF remote located in Dining Room with discreet Tunable White & RGB Rear Light (shows up as separate lights)."
  device_description: Dining Room Light - Main Light
  friendly_name: "Dining Room Light - Tunable White"    # Put the name that you want to see in Home Assistant.
  device_name_rgb: diningroomlightrgb
  device_description_rgb: "Dining Room Light - RGB Rear."    # Put the name that you want to see in Home Assistant.
  friendly_name_rgb: "Dining Room Light RGB"
  frequency_rgb: 100 Hz
  frequency_cw: 250 Hz
  frequency_ww: 250 Hz

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

wifi:
    ssid: !secret wifi_1st_ssid
    password: !secret wifi_1st_password

    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ap:
      ssid: ${device_ssid}
      password: !secret ap_password

captive_portal:

# Enable logging
# Example configuration entry
debug:

# Logger must be at least debug (default)
logger:
  level: debug

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

web_server:
  port: 80


output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO5
    max_power: 100%
    frequency: ${frequency_rgb}
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO4
    max_power: 100%
    frequency: ${frequency_rgb}
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO14
    max_power: 100%
    frequency: ${frequency_rgb}
  - platform: esp8266_pwm
    id: output_cold_white
    max_power: 100%
    frequency: ${frequency_cw}
    pin: GPIO12
  - platform: esp8266_pwm
    id: output_warm_white
    pin: GPIO13
    max_power: 100%
    frequency: ${frequency_ww}

globals:
  - id: last_light_on
    type: int
    restore_value: no
    initial_value: '1'

remote_receiver:
  pin:
    number: GPIO2
    inverted: True
  dump: 
  - nec
#  tolerance: 20%
#  buffer_size: 1kB
#  filter: 2us
#  idle: 4ms

binary_sensor:
  - platform: remote_receiver
    name: "On Button"
    nec:
      address: 0xFF00
      command: 0xC03F
    id: onbutton
    on_press:
      then:
        - lambda: |-
            if(id(last_light_on) == 1)
            {
            auto call = id(${device_name}).turn_on();
            call.perform();
            }
            else if (id(last_light_on) == 2)
            {
            auto call = id(${device_name_rgb}).turn_on();
            call.perform();
            }
       
  - platform: remote_receiver
    name: Off Button"
    nec:
      address: 0xFF00
      command: 0x20DF
    on_press:
      then:
        - lambda: |-
            if(id(last_light_on) == 1)
            {
            auto call = id(${device_name}).turn_off();
            call.perform();
            }
            else if (id(last_light_on) == 2)
            {
            auto call = id(${device_name_rgb}).turn_off();
            call.perform();
            }

  - platform: remote_receiver
    name: "Night Mode Button"
    nec:
      address: 0xFF00
      command: 0x906F
    on_press:
      then:
        - lambda: |-
            auto call = id(${device_name_rgb}).turn_off();
            call.perform();
            call = id(${device_name}).turn_on();
            call.set_color_temperature(500); // in mireds
            call.set_brightness(0.08);
            call.set_transition_length(1000); // in ms
            call.perform();
        - delay: 0.1s

  - platform: remote_receiver
    name: "Main Light Button"
    nec:
      address: 0xFF00
      command: 0x50AF
    on_press:
        then:
        - lambda: |-
            auto call = id(${device_name_rgb}).turn_off();
            call.perform();
            #define cwwwmode1 100mireds //Cool White
            #define cwwwmode2 300mireds //Natural White
            #define cwwwmode3 500mireds //Warm WHite
            static int cwwwmode = 1;
            call = id(${device_name}).turn_on();
            call.set_transition_length(1000);
            switch(cwwwmode)
            {
            case 1: call.set_color_temperature(100);
                    break;
            case 2: call.set_color_temperature(300);
                    break;
            case 3: call.set_color_temperature(500);
                    break;
            }
            cwwwmode++;
            if(cwwwmode == 4)
            {
              cwwwmode = 1;
            }
            call.perform();
            
  - platform: remote_receiver
    name: "Mood Light Button"
    nec:
      address: 0xFF00
      command: 0xD02F
    on_press:
      then:
        - lambda: |-
            auto call = id(${device_name}).turn_off();
            call.perform();
            #define Effect1 //Effect1
            #define Effect2 //Effect2
            #define Effect3 //Effect3
            #define Effect4 //Effect4
            static int effect = 1;
            call = id(${device_name_rgb}).turn_on();
            call.set_transition_length(500);
            switch(effect)
            {
            case 1: call.set_rgb(1.0, 0.0, 0.0);
            //call.set_effect(effect1);
                    break;
            case 2: call.set_rgb(1.0, 1.0, 0.0);
            //call.set_effect(effect2);
                    break;
            case 3: call.set_rgb(0.0, 1.0, 0.0);
            //call.set_effect(effect3);
                    break;
            case 4: call.set_rgb(0.0, 1.0, 1.0);
            //call.set_effect(effect4);
                    break;
            }
            effect++;
            if(effect == 5)
            {
              effect = 1;
            }
            call.perform();
            
  - platform: remote_receiver
    name: "RGB Colour Toggle Button"
    nec:
      address: 0xFF00
      command: 0x30CF
    on_press:
      then:
        - lambda: |-
            auto call = id(${device_name}).turn_off();
            call.perform();
            #define Color1 1.0, 0.0, 0.0 //Red
            #define Color2 1.0, 1.0, 0.0 //Yellow
            #define Color3 0.0, 1.0, 0.0 //Green
            #define Color4 0.0, 1.0, 1.0 //Cyan
            #define Color5 0.0, 0.0, 1.0 //Blue
            #define Color6 1.0, 0.0, 1.0 //Pink 
            static int color = 1;
            call = id(${device_name_rgb}).turn_on();
            call.set_transition_length(500);
            switch(color)
            {
            case 1: call.set_rgb(1.0, 0.0, 0.0);
                    break;
            case 2: call.set_rgb(1.0, 1.0, 0.0);
                    break;
            case 3: call.set_rgb(0.0, 1.0, 0.0);
                    break;
            case 4: call.set_rgb(0.0, 1.0, 1.0);
                    break;
            case 5: call.set_rgb(0.0, 0.0, 1.0);
                    break;
            case 6: call.set_rgb(1.0, 0.0, 1.0);
                    break;
            }
            color++;
            if(color == 7)
            {
              color = 1;
            }
            call.perform();

  - platform: remote_receiver
    name: "Warm Light Button"
    nec:
      address: 0xFF00
      command: 0x10EF
    id: warmbutton
    on_press:
      then:
        - lambda: |-
            if(id(last_light_on) == 1)
            {
            float current_temp = id(${device_name}).current_values.get_color_temperature();
            auto call = id(${device_name}).turn_on();
            call.set_color_temperature(current_temp + 100);
            call.set_transition_length(1000); // in ms
            call.perform();
            }
            else if (id(last_light_on) == 2)
            {
            float current_temp = id(${device_name_rgb}).current_values.get_color_temperature();
            auto call = id(${device_name_rgb}).turn_on();
            call.set_color_temperature(current_temp + 100);
            call.set_transition_length(1000); // in ms
            call.perform();
            }
        - delay: 0.01s

  - platform: remote_receiver
    name: "Cold Light Button"
    nec:
      address: 0xFF00
      command: 0xE01F
    id: coldbutton
    on_press:
      then:
        - lambda: |-
            if(id(last_light_on) == 1)
            {
            float current_temp = id(${device_name}).current_values.get_color_temperature();
            auto call = id(${device_name}).turn_on();
            call.set_color_temperature(current_temp - 100);
            call.set_transition_length(1000); // in ms
            call.perform();
            }
            else if (id(last_light_on) == 2)
            {
            float current_temp = id(${device_name_rgb}).current_values.get_color_temperature();
            auto call = id(${device_name_rgb}).turn_on();
            call.set_color_temperature(current_temp - 100);
            call.set_transition_length(1000); // in ms
            call.perform();
            }
        - delay: 0.01s

  - platform: remote_receiver
    name: "Bright+ Button"
    nec:
      address: 0xFF00
      command: 0xA05F
    id: brightbutton
    on_press:
      then:
        - lambda: |-
            if(id(last_light_on) == 1)
            {
            float brightness;
            auto call = id(${device_name}).turn_on();
            id(${device_name}).remote_values.as_brightness( &brightness );
            brightness += 0.1f;
            if( brightness > 1.0f )
            {
              brightness = 1.0f;
            }
            call.set_brightness( brightness );
            call.perform();
            }
            else if (id(last_light_on) == 2)
            {
            float brightness;
            auto call = id(${device_name_rgb}).turn_on();
            id(${device_name_rgb}).remote_values.as_brightness( &brightness );
            brightness += 0.1f;
            if( brightness > 1.0f )
            {
              brightness = 1.0f;
            }
            call.set_brightness( brightness );
            call.perform();
            }
        - delay: 0.01s

  - platform: remote_receiver
    name: "Dim- Button"
    nec:
      address: 0xFF00
      command: 0x609F
    id: dimbutton
    on_press:
      then:
        - lambda: |-
            if(id(last_light_on) == 1)
            {
            float brightness;
            auto call = id(${device_name}).turn_on();
            id(${device_name}).remote_values.as_brightness( &brightness );
            brightness -= 0.1f;
            if( brightness < 0.0f )
            {
              brightness = 0.0f;
            }
            call.set_brightness( brightness );
            call.perform();
            }
            else if (id(last_light_on) == 2)
            {
            float brightness;
            auto call = id(${device_name_rgb}).turn_on();
            id(${device_name_rgb}).remote_values.as_brightness( &brightness );
            brightness -= 0.1f;
            if( brightness < 0.0f )
            {
              brightness = 0.0f;
            }
            call.set_brightness( brightness );
            call.perform();
            }
        - delay: 0.01s

light:
  - platform: cwww
    name: ${friendly_name}    # Put the name that you want to see in Home Assistant.
    id: ${device_name}    # id used in esphome.
    cold_white: output_cold_white
    warm_white: output_warm_white
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
    constant_brightness: true
    default_transition_length: 1s
    on_turn_on:
    - globals.set:
        id: last_light_on
        value: '1'
  - platform: rgb
    name: ${friendly_name_rgb}
    id: ${device_name_rgb}
    red: output_red
    green: output_green
    blue: output_blue
    default_transition_length: 0.5s
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
    - globals.set:
        id: last_light_on
        value: '2'

## TODO's remote_receiver colour change for rgb light
## Effects to implement